/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea2;

import java.text.DecimalFormat;  
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public Object[][] tableData2;
    public SistemasdeEcuaciones resolver3;
    public SistemasdeEcuaciones resolver2;
    
    public GUI() {
       
        initComponents();
        
        matriz1.getTableHeader().setVisible(false);
        matriz1.setShowVerticalLines(true);
        matriz1.setShowHorizontalLines(true);
        DefaultTableModel model = new DefaultTableModel(0,0);
        matriz1.setModel(model);
        
        matriz2.getTableHeader().setVisible(false);
        matriz2.setShowVerticalLines(true);
        matriz2.setShowHorizontalLines(true);
        matriz2.setModel(model);
        b2.getTableHeader().setVisible(false);
        b2.setShowHorizontalLines(true);
        b2.setModel(model);
        L2.getTableHeader().setVisible(false);
        L2.setShowVerticalLines(true);
        L2.setShowHorizontalLines(true);
        L2.setModel(model);
        U2.getTableHeader().setVisible(false);
        U2.setShowVerticalLines(true);
        U2.setShowHorizontalLines(true);
        U2.setModel(model);
    
        
        matriz3.getTableHeader().setVisible(false);
        matriz3.setShowVerticalLines(true);
        matriz3.setShowHorizontalLines(true);
        matriz3.setModel(model);
        b3.getTableHeader().setVisible(false);
        b3.setShowHorizontalLines(true);
        b3.setModel(model);
        
        L3.getTableHeader().setVisible(false);
        L3.setShowVerticalLines(true);
        L3.setShowHorizontalLines(true);
        L3.setModel(model);
        
        U3.getTableHeader().setVisible(false);
        U3.setShowVerticalLines(true);
        U3.setShowHorizontalLines(true);
        U3.setModel(model);
        
        matriz4.getTableHeader().setVisible(false);
        matriz4.setShowVerticalLines(true);
        matriz4.setShowHorizontalLines(true);
        matriz4.setModel(model);
        Lb3.getTableHeader().setVisible(false);
        Lb3.setShowHorizontalLines(true);
        Lb3.setModel(model);
        
        matriz5.getTableHeader().setVisible(false);
        matriz5.setShowVerticalLines(true);
        matriz5.setShowHorizontalLines(true);
        matriz5.setModel(model);
        Ub3.getTableHeader().setVisible(false);
        Ub3.setShowHorizontalLines(true);
        Ub3.setModel(model);
        
        matriz6.getTableHeader().setVisible(false);
        matriz6.setShowVerticalLines(true);
        matriz6.setShowHorizontalLines(true);
        matriz6.setModel(model);

        
        U4.getTableHeader().setVisible(false);
        U4.setShowVerticalLines(true);
        U4.setShowHorizontalLines(true);
        U4.setModel(model);
        
        L5.getTableHeader().setVisible(false);
        L5.setShowVerticalLines(true);
        L5.setShowHorizontalLines(true);
        L5.setModel(model);
        
        U5.getTableHeader().setVisible(false);
        U5.setShowVerticalLines(true);
        U5.setShowHorizontalLines(true);
        U5.setModel(model);
        
        inversaL.getTableHeader().setVisible(false);
        inversaL.setShowVerticalLines(true);
        inversaL.setShowHorizontalLines(true);
        inversaL.setModel(model);
        
        inversaU.getTableHeader().setVisible(false);
        inversaU.setShowVerticalLines(true);
        inversaU.setShowHorizontalLines(true);
        inversaU.setModel(model);
        
        base.getTableHeader().setVisible(false);
        base.setShowVerticalLines(true);
        base.setShowHorizontalLines(true);
        base.setModel(model);
        
        
        
   
    }
    void convertToFloat(Object[][] matriz,float[][] L){
        
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aplicacion1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        matriz1 = new javax.swing.JTable();
        rango1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        agregarMatriz1 = new javax.swing.JButton();
        verificar = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane11 = new javax.swing.JScrollPane();
        base = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        generarbase = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        matriz2 = new javax.swing.JTable();
        rango2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        agregarMatriz2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        b2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        L2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        U2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        pasoY = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        resultado2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LU2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        matriz3 = new javax.swing.JTable();
        rango3 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        agregarMatriz3 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        matriz4 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        matriz5 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pasoMatriz1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        b31 = new javax.swing.JScrollPane();
        Lb3 = new javax.swing.JTable();
        b32 = new javax.swing.JScrollPane();
        Ub3 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        b3 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        L3 = new javax.swing.JTable();
        jScrollPane17 = new javax.swing.JScrollPane();
        U3 = new javax.swing.JTable();
        LU3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        resultadoU = new javax.swing.JTextArea();
        jScrollPane25 = new javax.swing.JScrollPane();
        resultadoU1 = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        matriz6 = new javax.swing.JTable();
        rango4 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        agregarMatriz4 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane20 = new javax.swing.JScrollPane();
        U4 = new javax.swing.JTable();
        jScrollPane21 = new javax.swing.JScrollPane();
        L5 = new javax.swing.JTable();
        jScrollPane22 = new javax.swing.JScrollPane();
        U5 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        inversaL = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane24 = new javax.swing.JScrollPane();
        inversaU = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        calcularInvL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Aplicacion 1"); // NOI18N

        jToggleButton1.setText("Aceptar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Siguiente paso");

        matriz1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(matriz1);

        rango1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        rango1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rango1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tamaño");

        agregarMatriz1.setText("Crear Matriz");
        agregarMatriz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMatriz1ActionPerformed(evt);
            }
        });

        verificar.setText("Verificar");

        jLabel30.setText("Linealmente independiente o dependiente");

        result.setText("[resultado]");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "R2", "R3" }));

        base.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane11.setViewportView(base);

        jLabel31.setText("Base");

        generarbase.setText("Generar base");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rango1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(agregarMatriz1))
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(verificar)
                                    .addComponent(result)))
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)
                            .addComponent(generarbase))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton1)))
                .addGap(36, 36, 36)
                .addComponent(jToggleButton2)
                .addGap(221, 221, 221))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rango1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(agregarMatriz1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(result)
                        .addGap(18, 18, 18)
                        .addComponent(verificar)))
                .addGap(29, 29, 29)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generarbase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2))
                .addGap(34, 34, 34))
        );

        aplicacion1.addTab("Aplicacion 1", jPanel5);

        matriz2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(matriz2);

        rango2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        rango2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rango2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tamaño");

        agregarMatriz2.setText("Crear Matriz");
        agregarMatriz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMatriz2ActionPerformed(evt);
            }
        });

        b2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(b2);

        L2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(L2);

        U2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(U2);

        jLabel2.setText("=");

        pasoY.setText("Calcular");
        pasoY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasoYActionPerformed(evt);
            }
        });

        jLabel8.setText("Resultado X");

        jLabel12.setText("Resultado Y");

        LU2.setText("Calcular LU");
        LU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LU2ActionPerformed(evt);
            }
        });

        jLabel5.setText("L");

        jLabel6.setText("U");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane14.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane15.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(resultado2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultado)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rango2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(agregarMatriz2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(LU2)))
                .addGap(279, 279, 279))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(pasoY))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(147, 147, 147)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rango2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(agregarMatriz2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LU2)
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jScrollPane14))
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultado)
                    .addComponent(resultado2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pasoY)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        aplicacion1.addTab("Aplicacion 2", jPanel6);

        matriz3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(matriz3);

        rango3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        rango3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rango3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Tamaño");

        agregarMatriz3.setText("Crear Matriz");
        agregarMatriz3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMatriz3ActionPerformed(evt);
            }
        });

        matriz4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(matriz4);

        matriz5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(matriz5);

        jLabel10.setText("L");

        jLabel11.setText("U");

        pasoMatriz1.setText("Mostrar solucion");
        pasoMatriz1.setActionCommand("Mostrar Solucion");
        pasoMatriz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasoMatriz1ActionPerformed(evt);
            }
        });

        jLabel13.setText("=");

        Lb3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        b31.setViewportView(Lb3);

        Ub3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        b32.setViewportView(Ub3);

        jLabel14.setText("=");

        b3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane13.setViewportView(b3);

        jLabel17.setText("=");

        L3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane16.setViewportView(L3);

        U3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane17.setViewportView(U3);

        LU3.setText("Calcular LU");
        LU3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LU3ActionPerformed(evt);
            }
        });

        jLabel20.setText("L");

        jLabel21.setText("U");

        jLabel22.setText("b");

        jLabel23.setText("b");

        jLabel24.setText("b");

        resultadoU.setColumns(20);
        resultadoU.setRows(5);
        jScrollPane19.setViewportView(resultadoU);

        resultadoU1.setColumns(20);
        resultadoU1.setRows(5);
        jScrollPane25.setViewportView(resultadoU1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(213, 213, 213)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b31, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(b32, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(127, 127, 127)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rango3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(agregarMatriz3))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(171, 171, 171)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(236, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(LU3)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(pasoMatriz1)
                        .addGap(583, 583, 583))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20)
                                .addComponent(jLabel21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rango3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addComponent(agregarMatriz3))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel17)))
                .addGap(10, 10, 10)
                .addComponent(LU3)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b32, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel14))
                            .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel23))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel13))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                        .addComponent(b31, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))))))
                .addGap(47, 47, 47)
                .addComponent(pasoMatriz1)
                .addGap(94, 94, 94))
        );

        aplicacion1.addTab("Aplicacion 3", jPanel7);

        matriz6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane12.setViewportView(matriz6);

        rango4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        rango4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rango4ActionPerformed(evt);
            }
        });

        jLabel15.setText("Tamaño");

        agregarMatriz4.setText("Crear Matriz");
        agregarMatriz4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMatriz4ActionPerformed(evt);
            }
        });

        jLabel25.setText("Inversa de LU");

        U4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane20.setViewportView(U4);

        L5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane21.setViewportView(L5);

        U5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane22.setViewportView(U5);

        jLabel16.setText("L");

        jLabel18.setText("U");

        inversaL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane23.setViewportView(inversaL);

        jLabel19.setText("=");

        jLabel27.setText("Inversa");

        jLabel28.setText("=");

        inversaU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane24.setViewportView(inversaU);

        jLabel29.setText("Inversa");

        calcularInvL.setText("Calcular");
        calcularInvL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularInvLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rango4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(agregarMatriz4))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(calcularInvL)))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel27))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(rango4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15))
                                        .addGap(18, 18, 18)
                                        .addComponent(agregarMatriz4))
                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(jLabel16)))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addGap(65, 65, 65)
                                    .addComponent(jLabel19)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(41, 41, 41))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel29))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel28))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addComponent(calcularInvL)
                .addGap(103, 103, 103))
        );

        aplicacion1.addTab("Aplicacion 4", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(aplicacion1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(aplicacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        aplicacion1.getAccessibleContext().setAccessibleName("Aplicacion 1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarMatriz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMatriz1ActionPerformed
        int rango = Integer.valueOf((String)rango1.getSelectedItem());
        DefaultTableModel model = new DefaultTableModel(rango,rango);
        matriz1.setModel(model);

    }//GEN-LAST:event_agregarMatriz1ActionPerformed

    private void rango1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rango1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rango1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) matriz1.getModel();
        int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
        tableData2 = new Object[nRow][nCol];
        for (int i = 0 ; i < nRow ; i++){
            for (int j = 0 ; j < nCol ; j++){
                tableData2[i][j] = dtm.getValueAt(i,j);}}

        dtm.setValueAt("0", 1, 1);
        matriz1.setModel(dtm);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void LU3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LU3ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) matriz3.getModel();
       
        DefaultTableModel b3table = (DefaultTableModel) b3.getModel();
        int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
        DefaultTableModel dtm2 = new DefaultTableModel(nRow,nCol);
        DefaultTableModel dtm3 =  new DefaultTableModel(nRow,nCol);
        float[][] tabla3 = new float[nRow][nCol];
        float[] b3 = new float[nRow];
        
   
        for (int i = 0 ; i < nRow ; i++){
            for (int j = 0 ; j < nCol ; j++){
 
            
                tabla3[i][j] = Float.parseFloat(dtm.getValueAt(i,j).toString());
            }
        }
       for(int t = 0; t <nRow;t++){
            b3[t] = Float.parseFloat(b3table.getValueAt(t,0).toString());
        }
        resolver3 = new SistemasdeEcuaciones(Integer.parseInt(rango3.getSelectedItem().toString()),tabla3,b3);
        float [][] MatrizU = resolver3.matrizU();
        float [][] MatrizL = resolver3.L;
        
        
        for(int i =0; i< nRow; i++){
            for (int j=0; j < nCol;j++){
                float f =MatrizL[i][j];
                String k = Float.toString(f);
                dtm2.setValueAt(k,i,j);
            }
        }
        L3.setModel(dtm2);
 
        for(int i =0; i< nRow; i++){
            for (int j=0; j < nCol;j++){
                float f =MatrizU[i][j];
                String k = Float.toString(f);
                dtm3.setValueAt(k,i,j);
            }
        }
        U3.setModel(dtm3);
        
        
        
        
        
    }//GEN-LAST:event_LU3ActionPerformed

    private void agregarMatriz3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMatriz3ActionPerformed
        int rango = Integer.valueOf((String)rango3.getSelectedItem());
        DefaultTableModel model = new DefaultTableModel(rango,rango);
        matriz3.setModel(model);
        model = new DefaultTableModel(rango,1);
        b3.setModel(model);
    
    }//GEN-LAST:event_agregarMatriz3ActionPerformed

    private void rango3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rango3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rango3ActionPerformed

    private void rango4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rango4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rango4ActionPerformed

    private void agregarMatriz4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMatriz4ActionPerformed
        int rango = Integer.valueOf((String)rango4.getSelectedItem());
        DefaultTableModel model = new DefaultTableModel(rango,rango);
        matriz6.setModel(model);
    }//GEN-LAST:event_agregarMatriz4ActionPerformed

    private void agregarMatriz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMatriz2ActionPerformed
        int rango = Integer.valueOf((String)rango2.getSelectedItem());
        DefaultTableModel model = new DefaultTableModel(rango,rango);
        matriz2.setModel(model);
        model = new DefaultTableModel(rango,1);
        b2.setModel(model);
    }//GEN-LAST:event_agregarMatriz2ActionPerformed

    private void rango2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rango2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rango2ActionPerformed

    private void pasoMatriz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasoMatriz1ActionPerformed
        float [] vector1 = resolver3.vector;
        String [][] sistemaL = resolver3.AcomodarSistemaL(resolver3.L);
        DefaultTableModel dtm = (DefaultTableModel) matriz3.getModel();
       
        
        int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
        DefaultTableModel dtm2 = new DefaultTableModel(nRow,nCol);
        DefaultTableModel dtm3 =  new DefaultTableModel(nRow,nCol);
        DefaultTableModel bLmodel = new DefaultTableModel(nRow,1);
        DefaultTableModel bUmodel =  new DefaultTableModel(nRow,1);
        
        for(int i =0; i< nRow; i++){
            for (int j=0; j < nCol;j++){
                dtm2.setValueAt(sistemaL[i][j],i,j);
            }
        }
        matriz4.setModel(dtm2);
        for(int i=0;i<nRow;i++){
            bLmodel.setValueAt(Float.toString(vector1[i]), i, 0);
        }
        Lb3.setModel(bLmodel);
        
        float [] vector2 = resolver3.vector;
        float [] solucionL = resolver3.ResolversistemaL(resolver3.L, vector2);
        String h ="";
         if(nRow == 2){
             
             h+="y1 = "+solucionL[0]+" \n";
             h+="y2 = "+solucionL[1]+" \n";
  
           
        }
        if(nRow == 3){
            h+="y1 = "+solucionL[0]+" \n";
            h+="y2 = "+solucionL[1]+" \n";
            h+="y3 = "+solucionL[2]+" \n";
            
            
        }
        
        if(nRow == 4){
            h+="y1 = "+solucionL[0]+" \n";
            h+="y2 = "+solucionL[1]+" \n";
            h+="y3 = "+solucionL[2]+" \n";
            h+="y4 = "+solucionL[3]+" \n";
            
        }
        if(nRow == 5){
            h+="y1 = "+solucionL[0]+" \n";
            h+="y2 = "+solucionL[1]+" \n";
            h+="y3 = "+solucionL[2]+" \n";
            h+="y4 = "+solucionL[3]+" \n";
            h+="y5 = "+solucionL[4]+" \n";
              
        }
         resultadoU1.setText(h);
         
         
        String[][] sistemaU = resolver3.AcomodarSistemaU(resolver3.U);
        resolver3.mostrarSistemaU(sistemaU,solucionL);   
        float[] solucionU = resolver3.ResolverSistemaU(resolver3.U, solucionL);
        
        
        
        for(int i =0; i< nRow; i++){
            for (int j=0; j < nCol;j++){
                dtm3.setValueAt(sistemaU[i][j],i,j);
            }
        }
        matriz5.setModel(dtm3);
        for(int i=0;i<nRow;i++){
            bUmodel.setValueAt(Float.toString(solucionU[i]), i, 0);
        }
        Ub3.setModel(bUmodel);
    
        h ="";
         if(nRow == 2){
             
             h+="x1 = "+solucionU[0]+" \n";
             h+="x2 = "+solucionU[1]+" \n";
  
           
        }
        if(nRow == 3){
            h+="x1 = "+solucionU[0]+" \n";
            h+="x2 = "+solucionU[1]+" \n";
            h+="x3 = "+solucionU[2]+" \n";
            
            
        }
        if(nRow == 4){
            h+="x1 = "+solucionU[0]+" \n";
            h+="x2 = "+solucionU[1]+" \n";
            h+="x3 = "+solucionU[2]+" \n";
            h+="x4 = "+solucionU[3]+" \n";
            
        }
        if(nRow == 5){
            h+="x1 = "+solucionU[0]+" \n";
            h+="x2 = "+solucionU[1]+" \n";
            h+="x3 = "+solucionU[2]+" \n";
            h+="x4 = "+solucionU[3]+" \n";
            h+="x5 = "+solucionU[4]+" \n";
              
        }
         resultadoU.setText(h);
        
        
    }//GEN-LAST:event_pasoMatriz1ActionPerformed

    private void calcularInvLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularInvLActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) matriz6.getModel();
        
        int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
        MatrizP4 matriz = new MatrizP4(nRow);
        DefaultTableModel dtm2 = new DefaultTableModel(nRow,nCol);
        DefaultTableModel dtm3 =  new DefaultTableModel(nRow,nCol);
        DefaultTableModel dtm4 = new DefaultTableModel(nRow,nCol);
        DefaultTableModel dtm5 =  new DefaultTableModel(nRow,nCol);
        DefaultTableModel dtm6 =  new DefaultTableModel(nRow,nCol);
        float[][] tabla3 = new float[nRow][nCol];
        float[] b3 = new float[nRow];
   
        for (int i = 0 ; i < nRow ; i++){
            for (int j = 0 ; j < nCol ; j++){            
                matriz.setElement(i,j,Float.parseFloat(dtm.getValueAt(i,j).toString()));
            }
        }
        float [][] Upper = matriz.matrizU();
        for(int i =0; i< nRow; i++){
            for (int j=0; j < nCol;j++){
                dtm3.setValueAt(Upper[i][j],i,j);
            }
        }
        U5.setModel(dtm3);
        
        float [][] Lower = matriz.L;
        for(int i =0; i< nRow; i++){
            for (int j=0; j < nCol;j++){
                dtm2.setValueAt(Lower[i][j],i,j);
            }
        }
        L5.setModel(dtm2);
        float [][] LowerInversa = matriz.inversaL();
        for(int i =0; i< nRow; i++){
            for (int j=0; j < nCol;j++){
                dtm4.setValueAt(LowerInversa[i][j],i,j);
            }
        }
        inversaL.setModel(dtm4);
        float [][] UpperInversa = matriz.inversaU();
        for(int i =0; i< nRow; i++){
            for (int j=0; j < nCol;j++){
                dtm5.setValueAt(UpperInversa[i][j],i,j);
            }
        }
        inversaU.setModel(dtm5);
        
        float [][] MatrizInversa = matriz.multiplicacion(UpperInversa, LowerInversa);
        for(int i =0; i< nRow; i++){
            for (int j=0; j < nCol;j++){
                dtm6.setValueAt(MatrizInversa[i][j],i,j);
            }
        }
        U4.setModel(dtm6);
        
        
        
    }//GEN-LAST:event_calcularInvLActionPerformed

    private void LU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LU2ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) matriz2.getModel();
       
        DefaultTableModel b2table = (DefaultTableModel) b2.getModel();
        int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
        DefaultTableModel dtm2 = new DefaultTableModel(nRow,nCol);
        DefaultTableModel dtm3 =  new DefaultTableModel(nRow,nCol);
        float[][] tabla3 = new float[nRow][nCol];
        float[] b2 = new float[nRow];
   
        for (int i = 0 ; i < nRow ; i++){
            for (int j = 0 ; j < nCol ; j++){
 
            
                tabla3[i][j] = Float.parseFloat(dtm.getValueAt(i,j).toString());
            }
        }
//       for(int t = 0; t <nRow;t++){
//            b2[t] = Float.parseFloat(b2table.getValueAt(t,0).toString());
//        }
        resolver2 = new SistemasdeEcuaciones(Integer.parseInt(rango2.getSelectedItem().toString()),tabla3,b2);
        float [][] MatrizU = resolver2.matrizU();
        float [][] MatrizL = resolver2.L;
        
        
        for(int i =0; i< nRow; i++){
            for (int j=0; j < nCol;j++){
                float f =MatrizL[i][j];
                String k = Float.toString(f);
                dtm2.setValueAt(k,i,j);
            }
        }
        L2.setModel(dtm2);
 
        for(int i =0; i< nRow; i++){
            for (int j=0; j < nCol;j++){
                float f =MatrizU[i][j];
                String k = Float.toString(f);
                dtm3.setValueAt(k,i,j);
            }
        }
        U2.setModel(dtm3);
    }//GEN-LAST:event_LU2ActionPerformed

    private void pasoYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasoYActionPerformed

       
        DefaultTableModel b2table = (DefaultTableModel) b2.getModel();

        
        int rango = Integer.parseInt(rango2.getSelectedItem().toString());
        float [] x_array = new float[rango];
        float [] vector = new float[rango];
        for(int t = 0; t <rango;t++){
            vector[t] = Float.parseFloat(b2table.getValueAt(t,0).toString());
        }
        for(int k = 0; k < rango; k++)
        {
            x_array[k]=(float)k;
        }
        // Calcula Y
        
        float [] vector_y = new float[rango];
        String xString="";
        for(int i = 0; i < rango; i++)
        {
            float y;
            y = 1/resolver2.L[i][i];
            float sum =0;
            for(int j = 0; j < (i-1);j++)
            {
                sum = sum + (resolver2.L[i][j] * x_array[j]);
            }

            y = y * (vector[i] - sum);
            vector_y[i]=y;
            xString+="y"+i+" ="+y+'\n'; // muestra y
        }
        jTextArea1.setText(xString);
        // Calcular y
        float [][] Upper = resolver2.U;

        float [] vector_x = new float[rango];
        String yString="";
        for(int i = 0; i < rango; i++)
        {
            float x = 0;
            x = 1/Upper[i][i];
            float sum =0;
            int myJ = rango-1;
            
            
            for(int j = (i); j > 0;j--)
            {
                sum = sum + (Upper[i][j] * x_array[j]);
            }
            //System.out.println(x);
            x = x * (vector_y[i] - sum);
            vector_x[myJ] = x;
            yString +="x" +i+ " = " + x+'\n'; // muestra y

            myJ--;
        }
        jTextArea2.setText(yString);
        
    }//GEN-LAST:event_pasoYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable L2;
    private javax.swing.JTable L3;
    private javax.swing.JTable L5;
    private javax.swing.JButton LU2;
    private javax.swing.JButton LU3;
    private javax.swing.JTable Lb3;
    private javax.swing.JTable U2;
    private javax.swing.JTable U3;
    private javax.swing.JTable U4;
    private javax.swing.JTable U5;
    private javax.swing.JTable Ub3;
    private javax.swing.JButton agregarMatriz1;
    private javax.swing.JButton agregarMatriz2;
    private javax.swing.JButton agregarMatriz3;
    private javax.swing.JButton agregarMatriz4;
    private javax.swing.JTabbedPane aplicacion1;
    private javax.swing.JTable b2;
    private javax.swing.JTable b3;
    private javax.swing.JScrollPane b31;
    private javax.swing.JScrollPane b32;
    private javax.swing.JTable base;
    private javax.swing.JButton calcularInvL;
    private javax.swing.JButton generarbase;
    private javax.swing.JTable inversaL;
    private javax.swing.JTable inversaU;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTable matriz1;
    private javax.swing.JTable matriz2;
    private javax.swing.JTable matriz3;
    private javax.swing.JTable matriz4;
    private javax.swing.JTable matriz5;
    private javax.swing.JTable matriz6;
    private javax.swing.JButton pasoMatriz1;
    private javax.swing.JButton pasoY;
    private javax.swing.JComboBox rango1;
    private javax.swing.JComboBox rango2;
    private javax.swing.JComboBox rango3;
    private javax.swing.JComboBox rango4;
    private javax.swing.JLabel result;
    private javax.swing.JLabel resultado;
    private javax.swing.JLabel resultado2;
    private javax.swing.JTextArea resultadoU;
    private javax.swing.JTextArea resultadoU1;
    private javax.swing.JButton verificar;
    // End of variables declaration//GEN-END:variables
}
